### PR TITLE
Added an example to the documentation

### PR DESCRIPTION
**Pull request by sophiedeziel**
A helper method can help the views in a Rails app to stay clean and concise. 

I also added a precision in the "tags" section to tell that the code showed in the example following can be in a Rails initializer.

### CODE REVIEW

**Comment by kernow** [comment]
Thanks, could you removed the changes to the Gemfile from this commit, also add parenthesise to the method params in your example, e.g. method(arg) and all get this PR merged.

**Comment by sophiedeziel** [comment]
Yes of course! The gentile changes was a mistake by doing my commit too fast ;)

**Comment by sophiedeziel** [comment]
Gentile=Gemfile

**Comment by sophiedeziel** [comment]
Changes done!

**Pull request merged**
